name: Naver Keyword Tracker

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"  # 하루 4회 실행 (UTC 기준 → 한국 시간 오전 9시, 오후 3시, 밤 9시, 새벽 3시)
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: requests 설치
        run: pip install requests

      - name: 키워드 수집 스크립트 실행
        env:
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
        run: python scripts/naver_keyword_fetcher.py

      - name: 결과 로그 커밋 및 푸시 (토큰 사용)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add log.txt
          git commit -m "자동 키워드 로그 업데이트" || echo "변경사항 없음"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
